use std::cell::{RefCell, RefMut};
use std::rc::Rc;
use std::sync::Arc;
use parking_lot::{Mutex, RwLock};
use key_paths_derive::Kp;

#[derive(Debug, Kp)]
struct SomeComplexStruct {
    scsf: Option<Box<SomeOtherStruct>>,
    identity: String,
    scfs2: Arc<std::sync::Mutex<SomeOtherStruct>>,
    scfs3: Arc<std::sync::RwLock<SomeOtherStruct>>,
    // scfs4: Arc<RefMut<SomeOtherStruct>>,
    // scfs5: Option<RefCell<SomeOtherStruct>>,
    scfs6: Option<std::sync::Mutex<SomeOtherStruct>>,
    scfs7: Option<std::sync::RwLock<SomeOtherStruct>>,
    scfs8: Option<Mutex<SomeOtherStruct>>,
    scfs9: Option<RwLock<SomeOtherStruct>>,
    
    scfs10: std::sync::Mutex<Option<SomeOtherStruct>>,
    scfs11: std::sync::RwLock<Option<SomeOtherStruct>>,
    scfs12: Mutex<Option<SomeOtherStruct>>,
    scfs13: RwLock<Option<SomeOtherStruct>>,

    scfs14: Option<std::sync::Mutex<Option<SomeOtherStruct>>>,
    scfs15: Option<std::sync::RwLock<Option<SomeOtherStruct>>>,
    scfs16: Option<Mutex<Option<SomeOtherStruct>>>,
    scfs17: Option<RwLock<Option<SomeOtherStruct>>>,

    // Locks inside Arc (LockKp: root SomeComplexStruct, value SomeOtherStruct)
    scfs_arc_pl_m: Arc<Mutex<SomeOtherStruct>>,
    scfs_arc_pl_rw: Arc<RwLock<SomeOtherStruct>>,
    scfs_arc_std_mo: Arc<std::sync::Mutex<Option<SomeOtherStruct>>>,
    scfs_arc_std_rwo: Arc<std::sync::RwLock<Option<SomeOtherStruct>>>,
    scfs_arc_pl_mo: Arc<Mutex<Option<SomeOtherStruct>>>,
    scfs_arc_pl_rwo: Arc<RwLock<Option<SomeOtherStruct>>>,
    scfs_o_arc_std_m: Option<Arc<std::sync::Mutex<SomeOtherStruct>>>,
    scfs_o_arc_std_rw: Option<Arc<std::sync::RwLock<SomeOtherStruct>>>,
    scfs_o_arc_pl_m: Option<Arc<Mutex<SomeOtherStruct>>>,
    scfs_o_arc_pl_rw: Option<Arc<RwLock<SomeOtherStruct>>>,

    // Tokio: Option<Arc<tokio::sync::Mutex/RwLock<T>>> — produce AsyncLockKp (root SomeComplexStruct, value SomeOtherStruct)
    #[cfg(feature = "tokio")]
    scfs_t2: Option<Arc<tokio::sync::Mutex<SomeOtherStruct>>>,
    #[cfg(feature = "tokio")]
    scfs_t3: Option<Arc<tokio::sync::RwLock<SomeOtherStruct>>>,
}

#[derive(Debug, Kp)]
#[derive(Clone)]
struct SomeOtherStruct {
    sosf: Box<Option<OneMoreStruct>>,
}

#[derive(Debug, Clone, Kp)]
enum SomeEnum {
    A(String),
    B(Option<Arc<DarkStruct>>),
}

#[derive(Debug, Kp)]
#[derive(Clone)]
struct OneMoreStruct {
    omsf: Option<String>,
    omse: Option<SomeEnum>,
}

#[derive(Debug, Kp)]
struct DarkStruct {
    dsf: Option<String>,
}

impl SomeComplexStruct {
    fn new() -> Self {
        todo!()
        // Self {
        //     scsf: Some(SomeOtherStruct {
        //         sosf: Some(OneMoreStruct {
        //             omsf: Some(String::from("no value for now")),
        //             omse: Some(SomeEnum::B(Box::new(DarkStruct {
        //                 dsf: Some(String::from("dark field")),
        //             }))),
        //         }),
        //     }),
        //     identity: String::from("SomeComplexStruct"),
        //     scfs2: Arc::new(std::sync::RwLock::new(SomeOtherStruct {
        //         sosf: Some(OneMoreStruct {
        //             omsf: Some(String::from("no value for now")),
        //             omse: Some(SomeEnum::B(Box::new(DarkStruct {
        //                 dsf: Some(String::from("dark field")),
        //             }))),
        //         }),
        //     })),
        // }
    }
}
fn main() {
    let mut instance = SomeComplexStruct::new();
    
    SomeComplexStruct::scfs2()
        .then(SomeOtherStruct::sosf())
        .then(OneMoreStruct::omse())
        .then(SomeEnum::b()) // Generated by Casepaths macro
        .then(DarkStruct::dsf())
        .get_mut(&mut instance).map(|x| {
        *x = String::from("🖖🏿🖖🏿🖖🏿🖖🏿");
    });

    SomeComplexStruct::scfs3()
        .then(SomeOtherStruct::sosf())
        .then(OneMoreStruct::omse())
        .then(SomeEnum::b()) // Generated by Casepaths macro
        .then(DarkStruct::dsf())
        .get_mut(&mut instance).map(|x| {
        *x = String::from("🖖🏿🖖🏿🖖🏿🖖🏿");
    });
    

    // if let Some(omsf) = SomeComplexStruct::scfs2_lock()
    //     .then(SomeOtherStruct::sosf())
    //     .then(OneMoreStruct::omse())
    //     .then(SomeEnum::b()) // Generated by Casepaths macro
    //     .then(DarkStruct::dsf())
    //     .get_mut(&mut instance)
    // {
    //     *omsf = String::from("This is changed 🖖🏿🖖🏿🖖🏿🖖🏿🖖🏿🖖🏿🖖🏿");
    // }


    // println!("instance = {:?}", instance.scsf.unwrap().sosf.unwrap().omse.unwrap());
    // output - instance = B(DarkStruct { dsf: Some("🖖🏿🖖🏿🖖🏿🖖🏿") })
}
